---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/Mufa0/nav-quarkus.git
    app.quarkus.io/build-timestamp: 2021-04-30 - 11:13:21 +0000
    app.quarkus.io/commit-id: 0f1f632196564673a3b9e35257468e5cbb1bc068
  labels:
    app.kubernetes.io/name: nav-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: nav-quarkus
spec:
  ports:
  - name: http
    nodePort: 30100
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: nav-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/Mufa0/nav-quarkus.git
    app.quarkus.io/build-timestamp: 2021-04-30 - 11:13:21 +0000
    app.quarkus.io/commit-id: 0f1f632196564673a3b9e35257468e5cbb1bc068
  labels:
    app.kubernetes.io/name: nav-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: nav-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nav-quarkus
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/Mufa0/nav-quarkus.git
        app.quarkus.io/build-timestamp: 2021-04-30 - 11:13:21 +0000
        app.quarkus.io/commit-id: 0f1f632196564673a3b9e35257468e5cbb1bc068
      labels:
        app.kubernetes.io/name: nav-quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: nav-quarkus-secret
        - configMapRef:
            name: nav-quarkus-config
        image: mu7a/nav-quarkus:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        name: nav-quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
